- README.md
Added **JobScheduler** topic :+1:  and corresponding link for reference, also added to link to differentiate between **Service and IntentService** Class. :smile:
> Added JobScheduler Topic

- README.md
Reverts MindorksOpenSource/android-interview-questions#16
> Revert "update Readme.md"

- README.md
link to try/catch/finally clause explanation was added
> link to try/catch/finally clause explanation

- README.md
I have added some interview questions.
These questions are asked by me in a technical interview with a company in Sheffield, UK based company via Skype.
> Add More Questions

- README.md
- others/Solution.java
I sort all questions in Algorithms, Java and Android themes.
When review, please, pay attention for theme names. I think not all of them correct display containing questions.
Some themes contain only few questions, what indicates not complete coverage of them. I add some questions in next pull request.
Also, i deleted a Solution class. He's never been used?
> Questions sorted and grouped by themes. Removed repeated questions.

- README.md
Removed the duplicate information. Also fixed the ordering and categorization for some of the topics.
> Removing duplicates, Fixing ordering Fixes #59

- README.md
Adds a couple interesting questions relating to concurrency, architecture, exceptions, etc.
> Addition of several questions

- README.md
Changes on Title Heading and Sub Heading in OOP JAVA
> Changes on Title Heading and Sub Heading

- README.md
Reverts MindorksOpenSource/android-interview-questions#63
> Revert "Changes on Title Heading and Sub Heading"

- README.md
Reverts MindorksOpenSource/android-interview-questions#55
> Revert "Data structure implemented in java repository link added"

- README.md
Added MindOrks Chapters
1. Activity
2. Fragment
3. View
4. Layout
5. Persist Data
> Add MindOrks Chapters Link

- README.md
added question about displaying web content inside an app
attach article of [MindOrks](https://blog.mindorks.com/android-browser-lets-launch-chrome-custom-tabs-with-kotlin)
> added chrome custom tabs

- README.md
> add bold style to question

- README.md
[MindOrks](https://blog.mindorks.com/android-sqlite-database-in-kotlin) article
> added sqlite reference

- README.md
> Updated topics sources.

- README.md
Intent-Filter and Implicit vs Explicit Intent
> Two answer links added

- README.md
> Fix Deprecated typo

- README.md
source https://en.wikipedia.org/wiki/Quicksort
> corrected quick sort space complexity

- README.md
Hello @amitshekhariitbhu 
I have added 2 android interview questions which I faced in interviews but did not find here.
I will add more questions If I am able to recollect more. But I think rest of the questions I found already here :D
> Add more android interview questions and answers

- README.md
It is mentioned that enumerator have remove method which should instead be `don't` have
> Fix difference between Enumerator and Iterator

- README.md
Can you list 8 primitive types in java?
Present ans:
byte
short
int
long
float
double
char
String
boolean
Expected ans:
byte
short
int
long
float
double
char
boolean
String is not a primitive data type of Java.
This point may mislead a beginner.
> fixed issue related to one of the answer [Fixed Issue #134]
